# Deep Learning Fundamentals: Forward and Backward Propagation

This notebook demonstrates the basics of deep learning, including forward propagation, loss calculation, and backpropagation. Lets build a simple neural network from scratch using NumPy to grasp the underlying concepts without relying on high-level libraries.

The Whole world is an equation. We have a variables,weights(Coefficients of the variable) and Linearity(Degree of an equation) and the result of the relation of all 
these things together. AI is the thing which is parametrizing everything in the world. Visualize these variables, weights as a matrix ad add the Linearity to it.
Which will add us to a sensible equation. GPU's are fast matrix calculators so they are being used in the field of AI. Seamingly unconnected stuff is not really 
unconnected until we have an equation. The world is going to a field called Hypercustomization.

Andrej Karparthy: He was the co-founder of open-AI. He was the CTO of AI division of Tesla. He made a series of zero to hero. It is worth it.
ANN- Artificial Neural Network. Hidden Layers are also called as Black-Box. Gaussian Distribution. Probablity Distribution Function, Derivatives important topics
in this case.  If we have to be great in AI we have to be intimate with maths. We have to improve the grounding in math. Intractable Problem: y has no relationship with x.
We have an assumed function and training data for it. give input for that. compare that with the actual results. There will be errors. With that error, change the 
parameters of the assumed function. Repeat this for accurate and precise results(EPOC).

Jupyter notebook is a python interpretor which is widely used in Deep Learning Applications. Loss Function- We will never get correct output.Initiallly we do not know the ways so we start with random weights which result in y now we give that x and predict that y which is in lot of variation with ground one. The difference between the actual value and the predicted value for y is called the Loss Variable. We use cross entropy for benign or malignity of the function for classification of the error.
AI is an attempt to decrease the loss function to a bare minimum.

>```
>pip install numpy
>pip install micrograd
>pip install matplotlib
>```

Execute the above commands in your shell to install the requirements for this Lecture.

## Step 1: Import Libraries

We'll use NumPy for numerical computations.

In [ ]:
import numpy as np

## Step 2: Define Activation Functions

We'll use the sigmoid activation function and its derivative.

In [ ]:
def sigmoid(x):
    """Sigmoid activation function."""
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    """Derivative of the sigmoid function."""
    s = sigmoid(x)
    return s * (1 - s)

## Step 3: Initialize Parameters

We'll set up input features, target outputs, and initialize weights and biases.

In [ ]:
# Input data (features) and true label
x = np.array([
    [0.5, 1.5],
    [1.0, 2.0],
    [1.5, 0.5],
    [3.0, 1.0]
])  # Input: 4 samples, 2 features each
y_true = np.array([[0], [0], [1], [1]])  # True output labels

# Initialize weights and bias randomly
np.random.seed(0)  # For reproducibility
w = np.random.randn(2, 1)  # Weights: 2 inputs to 1 output neuron
b = np.random.randn(1)     # Bias term

## Step 4: Forward Propagation

Compute the outputs of the hidden and output layers.

In [ ]:
# Forward propagation
z = np.dot(x, w) + b                # Linear combination
y_pred = sigmoid(z)    # Sigmoid activation function

## Step 5: Compute Loss

We'll use Mean Squared Error (MSE) to measure the difference between predicted and actual values.

In [ ]:
loss = np.mean((y_pred - y_true) ** 2)

## Step 6: Backward Propagation

Calculate gradients and update weights and biases accordingly.

In [ ]:
d_loss = 2 * (y_pred - y_true) / y_pred.size          # Derivative of loss w.r.t y_pred

$$
\frac{\partial l}{\partial y_p} = \frac{2}{n}(y_p - y_t)
$$

In [ ]:
d_activation = sigmoid_derivative(y_pred)             # Derivative of sigmoid activation: sigmoid(z)[1-sigmoid(z)]
d_z = d_loss * d_activation                           # Chain rule: derivative w.r.t z
d_w = np.dot(x.T, d_z) / x.shape[0]                   # Gradient w.r.t weights
d_b = np.mean(d_z, axis=0)                            # Gradient w.r.t bias

## Step 7: Update weights and bias and show the output

In [ ]:
learning_rate = 0.1 #learning rate
w -= learning_rate * d_w
b -= learning_rate * d_b

print("Updated weights:\n", w)
print("Updated bias:\n", b)
print("Loss:", loss)
#standard gradient Descent(1/m(sigma(yp-yt)^2))(stable, but time taking)
#stocastic gradient descent one sample at a time(too many oscillation, fluctuation)(no sigma and 1/m)
#mini-batch gradient descent(grouping the batches)(no. of batches=samples/2^8, no. of normalizations that a neural network undergoes during loss computation)
#momentum gradient descent: previous gradient descents impact the present gradient descents
#now learning rate also changes for different weights different learning rates
#rms prop: (for learning rate decays)
#optimizer: Adam optimizer next session
#alpha is the learning rate
#AdaGrad and RmsProp combined we get ADAM optimizer to get adaptive to both sparse and dense gradients
#ADAM optimizer- Adaptive Moment Estimation
#m: gradient 1st moment 
#v: squared gradient 2nd moment
#alp
#CNN- ConvulutionalNeural Network
#GAN- Graphical Advisory Network
#ANN- for complex tasks such as the computation of mathematical equations
#CNN- works for images generally
#self-driving cars are extensions of CNN's, facial recognition, etc.,
#CNNs convulautional, pooling, ANNs. Convolution:
#kernel- a camera that scans the image bit by bit getting features, collected features become feature maps, movement of kernel from one bit to other is called striding. 
#the feature maps are consolidated into pools this is called as pooling layer. abstracts are removed at last, and it becomes more strong.
#ANN needs flattened input and there are set of outputs with their respective probabilities.
#overfitting training the ANN only for one or a closed aspects so we have dropout only considering that aspect more...

Updated weights:
 [[1.75704588]
 [0.38350287]]
Updated bias:
 [0.96932077]
Loss: 0.4484838343811475


In [17]:
import numpy as np
import torch
a=np.array([1,2,3])
print(a)
b=torch.tensor([1,2,3])
print(b)
print(type(a),type(b))
#matrix of zeros:

c=np.zeros((3,3))
print(c)
print(c.shape)

#in Tensor:
d=torch.tensor(np.zeros(3,3))
print(d)
print(d.shape)

[1 2 3]
tensor([1, 2, 3])
<class 'numpy.ndarray'> <class 'torch.Tensor'>
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


TypeError: Cannot interpret '3' as a data type